### ISSUE TITLE
Why did you fork this?

### ISSUE THREAD

**Issue by freekmurze** [hnassr/vue-laravel-table-component#1]
Hi,

I noticed that you forked our code and I wonder why? Is there any feature you were missing? We do accept PRs that add things to our code.

**Comment by hnassr** [comment]
Hi Freek,

I customize the pagination components to serve my work, I maked it to use the default laravel pagination, and I added a loading spinner when change the page.

And I make some changes in formatter method to pass the row data and to unescape the HTML tags.

If you accept these changes I will delete my package and adds the changes to your code.

Note: Im a big fan of your packages and component, thank you for all your contributions.

Example of my changes:
<img width="1185" alt="screen shot 2017-08-11 at 9 03 42 pm" src="https://user-images.githubusercontent.com/9513214/29226258-0251aab0-7eda-11e7-8909-2f4e8511c0ab.png">

**Comment by freekmurze** [comment]
First and foremost, if you're happy with your own fork, feel tree to continue to use it. 👍

Did you notice that in the past days we added a few cool features?
https://github.com/spatie/vue-table-component#retrieving-data-asynchronously
https://github.com/spatie/vue-table-component#formatting-values

And we're adding scoped slots so [you can customize the rendering of column](https://github.com/spatie/vue-table-component/blob/master/__tests__/components/table-component/TableComponent.test.js#L70-L78) next week.

Pagination is also now built in.

That being said here are my first thoughts on the features you added:

> I maked it to use the default laravel pagination, and I added a loading spinner when change the page

My feeling is that such functionality would not be accepted in our package. (de)activiting  the spinner is something that should be done inside the function that is being passed to the `data` prop of `TableComponent`

> unescape the HTML tags

This will be added soon

>  changes in formatter method

Which changes?

**Comment by hnassr** [comment]
Actually I will be happy if you change the pagination component to be more functionality, imagine that there is 100 page-links, its not make sense to show all page-links.

> And we're adding scoped slots so you can customize the rendering of column next week.

This will be awesome.

>> changes in formatter method

> Which changes?

pass the row data (object) to the formatter method, in case you need to use another attribute.

**Comment by freekmurze** [comment]
> Actually I will be happy if you change the pagination component to be more functionality, imagine that there is 100 page-links, its not make sense to show all page-links.

I'd accept a fully tested PR that makes the Paginator better. Or maybe there should be a way to pass a custom Paginator so users can do whatever they want. 😄 

> pass the row data (object) to the formatter method, in case you need to use another attribute.

I'd accept a fully tested PR for this 😄
